### ISSUE TITLE
Change License to allow vendoring with pip

### ISSUE THREAD

**Issue by vmuriart** [trustrachel/python-ntlm3#18]
Would it be possible to possibly change the license to allow for the package to be vendored with pip?

**Comment by sigmavirus24** [comment]
Since this is a fork (of https://code.google.com/archive/p/python-ntlm/), you would need the original project (and all of _its_ contributors) to agree to change the license. Then you would need all of the contributors to _this_ project to agree to that as well. It's not impossible, but it will be very very difficult. Why does this need to be vendored into pip?

**Comment by vmuriart** [comment]
Yea, we reached the same conclusion after further discussion. I was going
to close this.
It's to add ntlm authentication capability to pip.

**Comment by sigmavirus24** [comment]
@vmuriart yes, I found the issue after some work. For others that may be interested: https://github.com/pypa/pip/pull/3419

To be very very clear, this is for _proxy_ authentication with pip. It's absolutely a worthy goal but I'm uncertain how successful we will be in changing the license.

**Comment by vmuriart** [comment]
@sigmavirus24 correct, at this point looks like the best option would be to find an alternative ntlm library to use.
